### ISSUE TITLE
Changing the popup form

### ISSUE THREAD

**Issue by elmalki** [ClickerMonkey/dayspan#13]
I have an issue with the popup form, I'm working on my costum event form, I couldn't change the build in form with mine. The documentation is poor, there isn't enough examples on how to use slots and components, the package is great but it lacks the documentation.

**Comment by ClickerMonkey** [comment]
I think you meant to put this in https://github.com/ClickerMonkey/dayspan-vuetify - since this library is not the UI.

Sorry the documentation is poor, it won't be improved for a few months - between working on other projects and working on a `v-calendar` component for Vuetify I won't have much time. 

Thanks for using the package, I hope you find solution to your problems in a timely manner! The best thing you can do is just look at the components to see how things are structured. If you have a solid understanding of Vue components it shouldn't be too difficult.

**Comment by elmalki** [comment]
Thank you for your quick response, yeah I meant to post it in dayspan-vuetify. 
  I will read the components, I hope that the documentation will be clear so others can use your great work.
